### ISSUE TITLE
Unable to cache views because of reference in MenuServiceProvider

### ISSUE THREAD

**Issue by BartelSamyn-Sunday** [balajidharma/laravel-menu#3]
I am unable to perform the php artisan view:cache command because of line 39 in laravel-menu/src/MenuServiceProvider.php. The path is not found.

`$this->loadViewsFrom(__DIR__.'/resources/views', 'menu');`

**Comment by balajidharma** [comment]
@BartelSamyn-Sunday Fixed the issue on [v1.0.6](https://github.com/balajidharma/laravel-menu/releases/tag/v1.0.6)

Thank you
