### ISSUE TITLE
How to get menu icon?

### ISSUE THREAD

**Issue by nirjhareswar** [balajidharma/laravel-menu#4]
Greetings!

How do I get the SVG path of the menu items?
I tried taking the d= part from https://heroicons.com/ SVG, but it's not showing.
Please advise.

Best
Nir Banerjee

**Comment by balajidharma** [comment]
Try to render your icon similar to below component
https://github.com/balajidharma/basic-laravel-admin-panel/blob/2.x/resources/views/components/admin/base-icon.blade.php

You can try the admin panel with menu icons - https://github.com/balajidharma/basic-laravel-admin-panel

**Comment by nirjhareswar** [comment]
I am already using the admin panel, and while adding new menu item faced this issue.

I have seen the component already. I am talking about d= part. Like how do you generate this part:

M13,3V9H21V3M13,21H21V11H13M3,21H11V15H3M3,13H11V3H3V13Z (For Dashboard menu item)

I tried heroicons and took the d= part, added it in new menu item, but it's not rendering.

**Comment by balajidharma** [comment]
Try to use the https://pictogrammers.com/library/mdi/ icons. If you want different icons modify the template and use it.
